language: node_js
node_js: "11"
cache: yarn
before_script:
  - yarn
script: yarn build

before_deploy:
  - tar czvf umd.tar.gz -C build .
  - tar czvf es.tar.gz -C es .

deploy:
  - provider: releases
    api_key: "$GITHUB_KEY"
    file: 
      - "./umd.tar.gz"
      - "./es.tar.gz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_KEY"
    skip_cleanup: true
    on:
      tags: true
